#!/usr/bin/perl
use strict;
use warnings;
$|++;

###
# Load Modules
use Time::HiRes; # 5.8+
use IO::Socket; # 5.8+
###


###
# Constants
my $SLEEPTIME = 1000; # in microseconds
my $TIMEFRAME = 10; # in seconds
my $STARTTIME = time;
my $PRENAME = 'system-stats-linux' . '.';
###

###
# Variables
my $ENDTIME = time;
my $sock; # socket used to send to statsd
my $statsdport = 8125;
my $statsdhost = '127.0.0.1';
###

sub send_counter
{
  my $a = shift;
  my $b = shift;
  $sock->send("$PRENAME$a:$b|c|" . '@0.01');
}

# init the $sock variable
$sock = IO::Socket::INET->new(Proto => 'udp', PeerPort => $statsdport, PeerAddr => $statsdhost, Blocking=>0) or die "Could not create socket: $!\n";


while (1 == 1)
{
$STARTTIME = $ENDTIME;
$ENDTIME = $STARTTIME + 10;
print "start: " . time . "\n";

  while ($STARTTIME < $ENDTIME)
  {
    Time::HiRes::usleep($SLEEPTIME);
    $STARTTIME = time;
  } 

send_counter('time', time);
print "end  : " . time . "\n";
}
